### ISSUE TITLE
Switch to Public Domain License

### ISSUE THREAD

**Issue by breck7** [treenotation/jtree#28]
Here's a good model to base it on (https://home.cern/science/computing/birth-web/licensing-web)

> CERN relinquishes all intellectual property rights to this code, both source and binary and permission is given to anyone to use, duplicate, modify and distribute it.

**Comment by bb010g** [comment]
Would the [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) not be suitable?

**Comment by breck7** [comment]
@bb010g I really like CC0, but perhaps we can fork the ideas in it (and MIT), and come up with something a little bit better?

Here are a few of the features I'd like:
- short and self contained, like the MIT license, so although we can have a link to some website containing more information on the statement, it should work great standalone
- should allow links to other works you are using or referencing (think like the "References"/"Bibliography" section of academic papers), in a strongly typed language. If you forget to add a related work, someone can easily send a pull request with the fix.
- If you are using/incorporating another project which also uses the ASIF statement, you could combine the 2 files, or just add a link to the ASIF file of the project you are importing
- it should have strongly typed information like a release year, so future semantic technologies can parse that info more easily
- it should make a statement promoting the spirit of open source, like CC0 and MIT license
- it should be a public domain license

Here is a prototype of [ASIF](http://jtree.treenotation.org/designer/#grammar%0A%20asifNode%0A%20%20root%0A%20%20inScope%20whatIsAsif_63Node%20titleNode%20createdNode%20asifVersionNode%20doiIdNode%20commentNode%20referencesNode%0A%20keywordCell%0A%20anyCell%0A%20intCell%0A%20whatIsAsif_63Node%0A%20%20match%20whatIsAsif%3F%0A%20%20cells%20keywordCell%20anyCell%20anyCell%20anyCell%20anyCell%20anyCell%20anyCell%20anyCell%20anyCell%20anyCell%20anyCell%20anyCell%20anyCell%20anyCell%20anyCell%20anyCell%20anyCell%0A%20titleNode%0A%20%20cells%20keywordCell%20anyCell%20anyCell%20anyCell%0A%20createdNode%0A%20%20cells%20keywordCell%20intCell%0A%20asifVersionNode%0A%20%20cells%20keywordCell%20anyCell%0A%20doiIdNode%0A%20%20cells%20keywordCell%20anyCell%0A%20commentNode%0A%20%20cells%20keywordCell%20anyCell%20anyCell%20anyCell%20anyCell%20anyCell%20anyCell%20anyCell%20anyCell%20anyCell%20anyCell%0A%20referencesNode%0A%20%20inScope%20doiNode%20paperNode%20urlNode%0A%20%20cells%20keywordCell%0A%20doiNode%0A%20%20cells%20keywordCell%20anyCell%20anyCell%20anyCell%0A%20paperNode%0A%20%20cells%20keywordCell%20anyCell%20anyCell%20anyCell%0A%20urlNode%0A%20%20cells%20keywordCell%20anyCell%20anyCell%20anyCell%20anyCell%20anyCell%0Asample%0A%20whatIsAsif%3F%20Asif%20a%20public%20domain%20statement.%20This%20project%20is%20related%20into%20the%20public%20domain.%20blah%20blah%20blah.%0A%20title%20My%20Project%20Name%0A%20created%202019%0A%20asifVersion%201.0.0%0A%20doiId%20someDoiId%0A%20comment%20This%20work%20builds%20on%20the%20work%20of%20the%20following%20projects%0A%20references%0A%20%20doi%20someDoiREference%20Some%20Paper%0A%20%20paper%20http%3A%2F%2Farxiv.org%2FsomePAper%20Some%20paper%0A%20%20url%20http%3A%2F%2Fgithub.com%2Ffoobar%2Ffoo%20An%20open%20source%20project).

![Screen Shot 2019-09-05 at 10 53 23 AM](https://user-images.githubusercontent.com/74692/64379885-8f3d9800-cfcb-11e9-95a1-bbd1ca6f86fc.png)

The goal is to have something that does double duty 1) puts stuff into the public domain and 2) makes it easier to do bibtex and/or allows for easier intellectual honesty by making citing references easier (and fixing missing references easier).

**Comment by breck7** [comment]
Switched to Unlicense! I really like that one. Would still like some type of grammar as replacement for something like BibTex.

**Comment by breck7** [comment]
Closing this now with unlicense.

**Comment by bb010g** [comment]
Could you please avoid using Unlicense over something legally robust like CC0? See https://softwareengineering.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense/147120#147120 for why the Unlicense shouldn't be used. The legalese and length of the Creative Commons Zero license is unattractive to read, but the upshot is that you can actually say "this is effectively public domain under the CC0" and have it be true for everyone reading.

**Comment by bb010g** [comment]
Reference tooling like what you brought up is great, but it should be used *in addition to* a legally sound license, not to create or deviate from an existing crafted license. Satisfy the lawyers first, and then stick another file next to it with your license metadata and whatever else. [SPDX](https://spdx.org/licenses/) is probably worth looking into as part of a base of that sort of system, and [REUSE](https://reuse.software/spec/) currently uses SPDX to pursue better machine-readability for licensing at the file level if you want more ideas.

**Comment by breck7** [comment]
Thanks for the feedback!

> for why the Unlicense shouldn't be used.

The link you provided is written by a random stackoverflow user who specifically says they are not a lawyer. So if that's the best argument you have for not using the unlicense, we are going to stick with the unlicense.

> Satisfy the lawyers first

I can't think of why we should satisfy one class of people over another. Furthermore, the person you referenced above specifically says they are not a lawyer.

Thank you for the link to SPDX and REUSE. Seem interesting, but Unlicense is simpler and executed better, IMO.

**Comment by breck7** [comment]
I should add that I am very much a fan of CC, and thank you for the feedback here. But I wish CC was more like unlicense. It's much clearer, IMO. It's like the next version of CC.

**Comment by bb010g** [comment]
Here are some stronger sources on public domain / CC0 / the Unlicense than Stack Exchange:

* [The Open Source Initiative's FAQ entries on public domain and the CC0](https://opensource.org/faq#public-domain) (OSI is a non-profit focused on open source and the organization behind [the Open Source Definition](http://www.opensource.org/docs/osd) and [Approved License program](https://opensource.org/licenses)).

  > Thus we recommend that you always apply an approved Open Source license to software you are releasing, rather than try to waive copyright altogether. Using a clear, recognized Open Source license actually makes it easier for others to know that your software meets the Open Source Definition. It also enables the protection of attribution, and various other non-restrictive rights, that cannot be reliably enforced when there is no license.

  > For a detailed discussion of the complexities of the public domain and open source, search for the words "public domain" and "PD" in the subject headers of the [January 2012](https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2012-January/thread.html), [February 2012](https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2012-February/thread.html), and [March 2012](https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2012-March/thread.html) archives of the OSI License Review mailing list. And if the thought of reading all those conversations is daunting, please take that as more evidence that it's just better to use an approved Open Source License if you can!

  Note that this is mostly about the Creative Commons Zero license. The Unlicense is mentioned, but is not (yet) an approved OSI license.

* Linked from there, the OSI \[license-review\] list archives from [January 2012](https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2012-January/thread.html), [February 2012](https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2012-February/thread.html), and [March 2012](https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2012-March/thread.html), featuring 355 messages of hot license action.

  > At this time, we do not recommend releasing software using the the CC0 public domain dedication.

  > In February 2012, Creative Commons [submitted](https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2012-February/001409.html) CC0 to the OSI for approval as an open source license, requesting that the OSI evaluate the public license fallback section, since the rest of the text is a waiver of rights rather than a license. An unexpectedly intense and detailed discussion followed — search for "CC0" and "Creative Commons Zero" in the subject headers of the February 2012 and March 2012 archives of the OSI License Review mailing list.

  To list off the relevant threads:
    * [OSI, legal conditions outside the "four corners" of the license, and PD/CC 0 \[was Re: Can OSI specify that public domain is open source?\]](https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2012-January/001348.html)
    * [OSI recognition for Creative Commons Zero License?](https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2012-February/001409.html)
    * [Submitting CC0 for OSI approval](https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2012-February/001426.html)
    * [Request for consultation with CC on patent issue](https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2012-February/001517.html)
    * [CC withdrawl of CC0 from OSI process](https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2012-February/001565.html)
    * [Non-binding straw poll: Do you think CC0 should be approved?](https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2012-March/001612.html)

  > CC0 was not explicitly rejected, but the License Review Committee was unable to reach consensus that it should be approved, and Creative Commons eventually withdrew the application. The most serious of the concerns raised had to do with the effects of clause 4(a), which reads: *"No ... patent rights held by Affirmer are waived, abandoned, surrendered, licensed or otherwise affected by this document."*. While many open source licenses simply do not mention patents, it is exceedingly rare for open source licenses to explicitly disclaim any conveyance of patent rights, and the Committee felt that approving such a license would set a dangerous precedent, and possibly even weaken patent infringement defenses available to users of software released under CC0.

* [The Free Software Foundation's license commentary on the Unlicense](https://www.gnu.org/licenses/license-list.html#Unlicense)

  > If you want to release your work to the public domain, we recommend you use [CC0](https://www.gnu.org/licenses/license-list.html#CC0). CC0 also provides a public domain dedication with a fallback license, and is more thorough and mature than the Unlicense.

* [The FSF commentary on CC0](https://www.gnu.org/licenses/license-list.html#CC0)

  > If you want to release your non-software work to the public domain, we recommend you use CC0. For works of software it is not recommended, as CC0 has a term expressly stating it does not grant you any patent licenses.
  >
  > Because of this lack of patent grant, we encourage you to be careful about using software under this license; you should first consider whether the licensor might want to sue you for patent infringement. If the developer is refusing users patent licenses, the program is in effect a trap for users and users should avoid the program.

The Unlicense is not the next version of the Creative Commons Zero, because at the very least it's focused on software. This change of scope is not bad, but that's as a reflection of the legal complexities of license creation, or even public domain dedication. The problems with the Unlicense lie with pretending that real-world public domain dedication is a simple affair.

**Comment by bb010g** [comment]
If you like, [Zero-Clause BSD](https://opensource.org/licenses/0BSD) (SPDX [0BSD](https://spdx.org/licenses/0BSD)) is extremely small and OSI-approved.

This was found via [a comment on another Unlicense issue thread](https://github.com/docopt/docopt.rs/issues/1#issuecomment-428682183), which has this nice quote from rickmoen:

> […]I'm glad to clarify (and repeat) that I have nothing but respect for your and others' desire to achieve maximally permissive & terse software licensing. I'm totally sincere about that, and have consistently so said in public and private.
>
> My sharp criticism (call it condescension if you wish) has been restricted to ignominious failures to address that need, that fail for lack of attention to legal basics, such as [WTFPL](http://linuxmafia.com/faq/Licensing_and_Law/public-domain.html#wtfpl) and [Unlicense](http://linuxmafia.com/faq/Licensing_and_Law/public-domain.html#unlicense). Those licences' structural defects are both gravely fatal and pretty much not disputed by anyone familiar with basics of software licensing and copyright law -- which, like death and taxes, don't go away merely because one dislikes them.
>
> MIT License is excellent, of course -- and about 13 lines of standard ASCII text. Hypothetically switching to 0BSD would shrink that to about 10 lines, FWIW.

**Comment by breck7** [comment]
This is great work, thank you!

Now I'm learning toward switching to the Zero-Clause BSD (though I liked what is says is the old name better - Free Public License 1.0.0).

The 0BSD isn't as edgy as the unlicense, and loses some of that fighting spirit, but it seems to do the exact same thing in fewer words, so I like it.

**Comment by breck7** [comment]
I'm down to change to 0BSD perhaps if someone sends a PR.

Or if we go unlicense, perhaps someone could submit it for approval to OSI:

`As far as I know the Unlicense was never submitted for approval. It would therefore have to go through discussion on the license-review list before the OSI would formally approve it or record it as not approved. Anyone can submit a license for approval, it doesn't have to be the license author. If you would like to do that, this page: https://opensource.org/approval describes the process under "How to Submit a Request."`
