### ISSUE TITLE
What is the realtionship between jtree and pytree?

### ISSUE THREAD

**Issue by halloleo** [treenotation/jtree#57]
I am wondering how much use `pytree` is in comparison to `jtree`... `jtree` obviously looks a lot more complete for CLI use.

I want to begin playing with _tree notation_. Is the `pytree` experience feasible or should I go for a good starting experience with `jtree`?

**Comment by breck7** [comment]
> I want to begin playing with tree notation. Is the pytree experience feasible or should I go for a good starting experience with jtree?

I would recommend jtree for now. The pytree library only contains a few % of the functionality.

We have plans to build a "meta" library to make it easier to build implementations in a host language, but that's a few weeks away probably (https://github.com/treenotation/jtree/issues/37). Hopefully by next week we'll have the new homepage up, which will have links to all the implementations in various languages either from us or in progress by others. About 3 or 4 people have messaged me about writing a python implementation but I don't where those projects stand at the moment. Will start to better organize things soon.

**Comment by halloleo** [comment]
Makes sense. Thanks.
